"""CalSoft.pdf_generators.certificate — the B-12 certificate generator (composed from mixins)."""
"""CalSoft.pdf_generators — the B-12 hospital certificate generator + thin wrapper."""
import base64
import calendar
import io
import os
from datetime import datetime, timedelta
from decimal import Decimal
try:
    from zoneinfo import ZoneInfo
    EAT = ZoneInfo('Africa/Nairobi')
except ImportError:
    import pytz
    EAT = pytz.timezone('Africa/Nairobi')
import matplotlib
matplotlib.use('Agg')
import logging
import matplotlib.pyplot as plt
import numpy as np
import qrcode
from django.conf import settings
from django.core.files.storage import default_storage
from django.utils import timezone
from PIL import Image as PILImage
from reportlab.graphics import renderPDF
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.graphics.charts.linecharts import HorizontalLineChart
from reportlab.graphics.shapes import Drawing, Line, Rect
from reportlab.lib import colors
from reportlab.lib.colors import HexColor, black, blue, gray, green, red, white
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, inch, mm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.platypus import BaseDocTemplate, CondPageBreak, Frame, Image, KeepTogether, PageBreak, PageTemplate, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
logger = logging.getLogger(__name__)

# sibling modules in this package
from .signatures import SignatureImageLoader
from .watermark import _LogoWatermarkCanvas

# concern mixins (methods composed onto the generator below)
from .styles import StylesMixin
from .results import ResultsMixin
from .qr import QrMixin
from .header import HeaderMixin
from .sections import SectionsMixin
from .analysis import AnalysisMixin
from .signature_section import SignatureMixin
from .drift import DriftMixin


class BtwelveHospitalCertificateGenerator(
    StylesMixin, ResultsMixin, QrMixin, HeaderMixin, SectionsMixin, AnalysisMixin, SignatureMixin, DriftMixin,
):
    """
    PDF certificate generator with styled headers, background colors, and QR code for authenticity.
    """

    def __init__(self, session, context=None):
        """Initialize the certificate generator with proper certificate number handling."""
        self.session = session
        self.context = context or {}
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
        self.page_width, self.page_height = A4
        self.left_margin = 40
        self.right_margin = 40
        self.top_margin = 120
        self.bottom_margin = 40
        self.content_width = self.page_width - self.left_margin - self.right_margin

        # Declined flag — set before number resolution so helpers can branch on it
        self.is_declined = bool(self.context.get('is_declined', False))

        # For declined sessions use a reference number, not a certificate number.
        # The reference number comes from context (set by the view) or falls back
        # to a "REF-<pk>" pattern so the document is still traceable.
        if self.is_declined:
            ref = (
                self.context.get('certificate_number')  # view passes DECLINED-<pk> here
                or (f"REF-{self.session.id}" if hasattr(self.session, 'id') else "REF-000")
            )
            self.reference_number = str(ref)
            self.certificate_number = None          # explicitly absent for declined docs
        else:
            self.reference_number = None
            self.certificate_number = self._get_certificate_number_from_session()

        # Calculate failure statistics
        self.failure_stats = self.calculate_failure_statistics()
        self.is_failed_report = self.failure_stats['overall_failure_rate'] >= 0.40

        # Resolve logo once; reused by both the header and the watermark canvas
        self.logo_path = self._get_logo_path()

    def _get_certificate_number_from_session(self):
        """
        Get certificate number from the session object.
        The certificate number is generated by the backend (CalibrationSession model).
        This method just retrieves it safely.
        """
        try:
            # First priority: Get from session's certificate_number field
            if hasattr(self.session, 'certificate_number') and self.session.certificate_number:
                cert_num = str(self.session.certificate_number).strip()
                if cert_num and cert_num.lower() != 'none' and cert_num.lower() != 'null':
                    return cert_num

            # Second priority: Get from context (passed from view)
            if 'certificate_number' in self.context and self.context['certificate_number']:
                cert_num = str(self.context['certificate_number']).strip()
                if cert_num and cert_num.lower() != 'none':
                    return cert_num

            # Third priority: Check for certificate_number in related objects
            if hasattr(self.session, 'procedure') and self.session.procedure:
                if hasattr(self.session.procedure, 'certificate_number') and self.session.procedure.certificate_number:
                    cert_num = str(self.session.procedure.certificate_number).strip()
                    if cert_num and cert_num.lower() != 'none':
                        return cert_num

            # Fourth priority: Try to generate one if session ID exists
            if hasattr(self.session, 'id') and self.session.id:
                logger.warning(f"Certificate number not found for session {self.session.id}. Using fallback.")
                try:
                    # Try to import the model and generate
                    from CalSoft.models import CalibrationSession
                    cert_num = CalibrationSession.generate_certificate_number()
                    # Save it to the session
                    self.session.certificate_number = cert_num
                    self.session.save(update_fields=['certificate_number'])
                    logger.info(f"Generated and saved certificate number: {cert_num}")
                    return cert_num
                except ImportError as e:
                    logger.error(f"Cannot import CalibrationSession: {e}")
                except Exception as e:
                    logger.error(f"Failed to generate certificate number: {e}")

                # Alternative fallback
                year_prefix = datetime.now().strftime('%y')
                return f"BNH-CAL-{year_prefix}-{self.session.id:06d}"

            # Final fallback
            logger.error("No valid certificate number or session ID found")
            return "BNH-TEMP-0000"

        except Exception as e:
            logger.error(f"Error getting certificate number: {str(e)}")
            return "BNH-ERROR-0000"

    def generate_certificate(self):
        """Generate the calibration certificate PDF with background colors and QR code."""
        buffer = io.BytesIO()

        doc = BaseDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=self.left_margin,
            rightMargin=self.right_margin,
            topMargin=self.top_margin,
            bottomMargin=self.bottom_margin,
        )

        main_frame = Frame(
            self.left_margin,
            self.bottom_margin,
            self.content_width,
            self.page_height - self.top_margin - self.bottom_margin,
            leftPadding=0,
            rightPadding=0,
            topPadding=0,
            bottomPadding=0,
            id='main_frame'
        )

        template = PageTemplate(
            id='certificate_template',
            frames=[main_frame],
            onPage=self.draw_page_decoration
        )

        doc.addPageTemplates([template])

        elements = []
        elements.extend(self.build_certificate_title())
        elements.extend(self.build_certificate_number())

        elements.extend(self.build_three_section_table())
        elements.extend(self.build_section_with_header("CALIBRATOR & STANDARD INFORMATION", self.build_calibrator_info_content()))
        elements.extend(self.build_section_with_header("LINEARITY ANALYSIS", self.build_linearity_content()))
        elements.extend(self.build_section_with_header("DRIFT ANALYSIS", self.build_drift_analysis_content()))
        elements.extend(self.build_section_with_header("CALIBRATION RESULTS & STATISTICS", self.build_results_table()))

        # Add failure analysis section if there are failures
        if self.is_failed_report or self.failure_stats['failed_parameters']:
            elements.extend(self.build_section_with_header("FAILURE ANALYSIS", self.build_failure_analysis()))

        elements.extend(self.build_section_with_header("UNCERTAINTY BUDGET", self.build_uncertainty_table()))
        elements.extend(self.build_section_with_header("TRACEABILITY", self.build_traceability_content()))
        elements.extend(self.build_section_with_header("NOTES", self.build_notes_content()))
        elements.extend(self.build_signature_section())
        elements.extend(self.build_footer())

        from functools import partial
        wm_canvas = partial(_LogoWatermarkCanvas, logo_path=self.logo_path)
        doc.build(elements, canvasmaker=wm_canvas)
        buffer.seek(0)
        return buffer

    def _now_eat(self):
        """Return current datetime in East Africa Time (UTC+3)."""
        from django.utils import timezone as dj_tz
        return dj_tz.now().astimezone(EAT)

    def build_footer(self):
        """Build certificate footer with verification information."""

        footer_style = ParagraphStyle(
            name='LightFooter',
            fontSize=9,
            fontName='Helvetica',
            alignment=TA_CENTER,
            textColor=HexColor('#6b7280'),
            spaceAfter=3,
        )

        # Get calibrated by information
        calibrated_by = 'Biomedical Engineering Team'
        if hasattr(self.session, 'performed_by') and self.session.performed_by:
            user = self.session.performed_by
            if hasattr(user, 'get_full_name') and user.get_full_name():
                calibrated_by = user.get_full_name()
            elif user.first_name or user.last_name:
                calibrated_by = f"{user.first_name} {user.last_name}".strip()
            else:
                calibrated_by = user.username

        doc_id_label  = "Reference Number" if self.is_declined else "Certificate Number"
        doc_id_value  = self.reference_number if self.is_declined else self.certificate_number

        footer_text = f"""
        {doc_id_label}: {doc_id_value} | Generated on: {self._now_eat().strftime('%Y-%m-%d %H:%M EAT')}<br/>
        Calibrated by: {calibrated_by}<br/>
        <i>Certificate authenticity verified through QR code scanning and digital signature</i>
        """

        return [Spacer(1, 6), Paragraph(footer_text, footer_style)]


def generate_btwelve_certificate(session, context=None):
    """Generate a certificate using Department location from context."""
    generator = BtwelveHospitalCertificateGenerator(session, context)
    return generator.generate_certificate()
