# Generated by Django 5.2.15 on 2026-09-25 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('program', models.CharField(choices=[('ppm', 'Planned preventive maintenance'), ('calibration', 'Calibration')], max_length=20)),
                ('logic', models.CharField(choices=[('department', 'By department'), ('description', 'By equipment description')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('default_interval_months', models.PositiveSmallIntegerField(blank=True, help_text='Interval for descriptions without their own. Blank: such equipment is reported as unschedulable instead of guessed.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_plans_activated', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_plans_created', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_plans', to='workshop.workshop')),
            ],
            options={
                'ordering': ['workshop__name', 'program', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('interval_months', models.PositiveSmallIntegerField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_intervals', to='Inventory.equipmentdescription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='scheduling.schedulingplan')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('month_mask', models.PositiveSmallIntegerField(default=0, help_text='Bit n-1 set = month n allowed (Jan = bit 0).')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_rules', to='Inventory.department')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_rules', to='Inventory.equipmentdescription')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='scheduling.schedulingplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schedulingplan',
            constraint=models.UniqueConstraint(fields=('workshop', 'program', 'version'), name='scheduling_plan_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('workshop', 'program'), name='scheduling_one_active_plan'),
        ),
        migrations.AddConstraint(
            model_name='schedulinginterval',
            constraint=models.UniqueConstraint(fields=('plan', 'description'), name='scheduling_interval_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulinginterval',
            constraint=models.CheckConstraint(condition=models.Q(('interval_months__gte', 1), ('interval_months__lte', 60)), name='scheduling_interval_range'),
        ),
        migrations.AddConstraint(
            model_name='schedulingrule',
            constraint=models.UniqueConstraint(fields=('plan', 'department'), name='scheduling_rule_dept_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulingrule',
            constraint=models.UniqueConstraint(fields=('plan', 'description'), name='scheduling_rule_desc_unique'),
        ),
        migrations.AddConstraint(
            model_name='schedulingrule',
            constraint=models.CheckConstraint(condition=models.Q(('department__isnull', True), ('description__isnull', True), _connector='XOR'), name='scheduling_rule_one_group'),
        ),
    ]
