# Generated by Django 5.2.15 on 2026-09-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingplan',
            name='auto_new_groups',
            field=models.BooleanField(default=True, help_text='Give a group that appears later (a new description or department) months automatically, where the year has room. A group whose months are all unticked is left unscheduled on purpose.'),
        ),
    ]
