# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('role', models.CharField(choices=[('Tech', 'Technologist'), ('NIC', 'In-Charge'), ('HOD', 'Head of department')], max_length=50)),
                ('must_change_password', models.BooleanField(default=True)),
                ('has_uploaded_signature', models.BooleanField(default=False)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('level', models.CharField(blank=True, choices=[('Engineer', 'Engineer'), ('Engineer Incharge', 'Engineer Incharge')], help_text='Required for all Tech roles', max_length=50, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Only for In-Charge role', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, help_text='Required for all Tech roles', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['role', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
                ('signature_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_hash', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_user_drawn', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, unique=True)),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('pending_delete', models.BooleanField(default=False)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset',
                'verbose_name_plural': 'Password Resets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reset_code', 'is_used'], name='users_userp_reset_c_3bdf24_idx'), models.Index(fields=['user', 'expires_at'], name='users_userp_user_id_1b54ec_idx'), models.Index(fields=['token'], name='users_userp_token_7091e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILURE', 'Failed Login'), ('LOGOUT', 'Logout'), ('PASSWORD_RESET_REQUEST', 'Password Reset Requested'), ('PASSWORD_RESET_SUCCESS', 'Password Reset Successful'), ('PASSWORD_CHANGE', 'Password Changed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('SIGNATURE_REGENERATED', 'Signature Regenerated'), ('SIGNATURE_UPLOADED', 'Signature Uploaded'), ('PROFILE_UPDATED', 'Profile Updated'), ('FIRST_LOGIN_SETUP', 'First Login Setup Completed')], max_length=30)),
                ('event_description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type'], name='users_users_user_id_5892c9_idx'), models.Index(fields=['timestamp'], name='users_users_timesta_81fb53_idx'), models.Index(fields=['ip_address'], name='users_users_ip_addr_08e4d4_idx')],
            },
        ),
    ]
