# Generated by Django 5.2.10 on 2026-01-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignature',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image (preferred for PyInstaller apps)', null=True),
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Traditional file storage (fallback)', null=True, upload_to='signatures/'),
        ),
    ]
