# Generated by Django 5.2.10 on 2026-02-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersignature_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sidebar_collapsed',
            field=models.BooleanField(default=False, help_text='Whether sidebar is collapsed by default'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', help_text='User preferred theme mode', max_length=10),
        ),
    ]
