# Generated by Django 5.2.15 on 2026-07-25 00:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_sidebar_collapsed_userprofile_theme_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('view_name', models.CharField(help_text="e.g. 'inventory', 'jobcard_waiting' — scopes filters to one page", max_length=100)),
                ('name', models.CharField(help_text="User-chosen label, e.g. 'My overdue equipment'", max_length=100)),
                ('filter_params', models.JSONField(blank=True, default=dict, help_text='Raw query-string params to re-apply')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'view_name'], name='users_saved_user_id_178a5a_idx')],
            },
        ),
    ]
