# Generated by Django 5.2.17 on 2026-09-26 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_copy_signature_files_into_database"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersecuritylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Successful Login"),
                    ("LOGIN_FAILURE", "Failed Login"),
                    ("LOGOUT", "Logout"),
                    ("PASSWORD_RESET_REQUEST", "Password Reset Requested"),
                    ("PASSWORD_RESET_SUCCESS", "Password Reset Successful"),
                    ("PASSWORD_CHANGE", "Password Changed"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("SIGNATURE_REGENERATED", "Signature Regenerated"),
                    ("SIGNATURE_UPLOADED", "Signature Uploaded"),
                    ("PROFILE_UPDATED", "Profile Updated"),
                    ("FIRST_LOGIN_SETUP", "First Login Setup Completed"),
                    ("SESSION_EXPIRED", "Signed Out After Inactivity"),
                    ("TWO_FACTOR_ENABLED", "Two-Factor Sign-In Turned On"),
                    ("TWO_FACTOR_DISABLED", "Two-Factor Sign-In Turned Off"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TwoFactorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.CharField(max_length=64)),
                ("recovery_codes", models.JSONField(default=list)),
                ("last_used_step", models.BigIntegerField(default=0)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
