# Generated by Django 5.2.15 on 2026-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_copy_signature_files_into_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_deputy_hod',
            field=models.BooleanField(default=False, help_text='Copied on emails sent to the Head of Department'),
        ),
    ]
