# Generated by Django 5.2.15 on 2026-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_muted',
            field=models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list),
        ),
    ]
