# Generated by Django 5.2.15 on 2026-09-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_email_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_muted',
        ),
    ]
