# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CalSoft', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSchedule',
            fields=[
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_month', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending (includes Pushed)'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('pushed', 'Pushed (treated as Pending)'), ('pending_approval', 'Pending Approval')], default='pending', max_length=20)),
                ('planning_logic', models.CharField(blank=True, choices=[('description_based', 'Description Based'), ('date_based', 'Date Based')], help_text='Logic used to plan this schedule (e.g., description-based)', max_length=50, null=True)),
                ('calibration_period', models.PositiveIntegerField(choices=[(6, '6 Months'), (12, '12 Months')], default=12, help_text='Calibration interval in months')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Estimated duration for the calibration procedure', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Description of the calibration schedule')),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('generation_source', models.CharField(choices=[('manual', 'Manual Creation'), ('normalization', 'Created by Normalization'), ('signal', 'Auto-created after Completion'), ('initialization', 'Initial System Setup'), ('bulk_import', 'Bulk Import')], db_index=True, default='manual', help_text='How this schedule was created - signal-created schedules are protected from normalization', max_length=20)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='If True, this schedule cannot be modified by normalization or bulk operations')),
                ('expected_calibration_date', models.DateField(blank=True, help_text='Expected calibration date calculated from parent completion (for signal-created schedules)', null=True)),
                ('generation_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this schedule was generated/created')),
                ('calibration_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calschedules_schedules', to='CalSoft.calibrationprocedure')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calschedules_schedules', to='Inventory.equipment')),
                ('parent_schedule', models.ForeignKey(blank=True, help_text='The completed schedule that triggered auto-creation of this schedule (for signal-created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schedules', to='calSchedules.calibrationschedule')),
                ('workshop', models.ForeignKey(help_text='Workshop managing this calibration schedule', on_delete=django.db.models.deletion.CASCADE, related_name='calschedules_schedules', to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'Calibration Schedule',
                'verbose_name_plural': 'Calibration Schedules',
                'ordering': ['scheduled_month', 'equipment'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pending_delete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calschedules_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='calSchedules.calibrationschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['workshop', 'scheduled_month'], name='calSchedule_worksho_70f6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['equipment', 'status'], name='calSchedule_equipme_7324fe_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['generation_source', 'status'], name='calSchedule_generat_e5fb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['is_locked'], name='calSchedule_is_lock_993e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['scheduled_month', 'status'], name='calSchedule_schedul_2c0836_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calibrationschedule',
            unique_together={('equipment', 'scheduled_month')},
        ),
    ]
