# Generated by Django 4.2.30 on 2026-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calSchedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationschedule',
            name='logic_change_warning',
            field=models.TextField(blank=True, default='', help_text='Warning message set when planning_logic changes on an existing schedule. Cleared once the schedule is re-normalized under the new logic.'),
        ),
        migrations.AddField(
            model_name='calibrationschedule',
            name='previous_planning_logic',
            field=models.CharField(blank=True, default='', help_text='The planning logic that was in use before the last logic change (for smart reorganizer)', max_length=50),
        ),
        migrations.AlterField(
            model_name='calibrationschedule',
            name='generation_source',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('normalization', 'Created by Normalization'), ('signal', 'Auto-created after Completion'), ('initialization', 'Initial System Setup'), ('bulk_import', 'Bulk Import'), ('auto_advance', 'Auto-Advanced (Group-Aware)'), ('reconciliation', 'Created by Reconciliation'), ('group_alignment', 'Aligned to Group Month'), ('group_fix', 'Fixed Group Alignment'), ('locker', 'Created by Locker'), ('job_card', 'Triggered by Job Card Completion')], db_index=True, default='manual', help_text='How this schedule was created - signal-created schedules are protected from normalization', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationschedule',
            name='planning_logic',
            field=models.CharField(blank=True, choices=[('description_based', 'Description Based'), ('date_based', 'Date Based'), ('department', 'Date Based (Department)'), ('description', 'Description Based (Alias)')], help_text='Logic used to plan this schedule (e.g., description-based)', max_length=50, null=True),
        ),
    ]
