# Generated by Django 4.2.30 on 2026-06-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calSchedules', '0002_calibrationschedule_logic_change_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('in_progress', 'In Progress'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
