# Generated by Django 5.2.15 on 2026-09-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calSchedules', '0003_alter_calibrationschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationschedule',
            name='due_month',
            field=models.DateField(blank=True, help_text='The month this schedule is due in its cycle. A manual push moves scheduled_month but not this, so the cycle continues from the slot.', null=True),
        ),
    ]
