# Generated by Django 5.2.17 on 2026-09-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_sync_poller_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("logo", models.ImageField(blank=True, upload_to="branding/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
