# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('jobcard', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('active_status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'db_table': 'machineReports_equipmentcategory',
                'ordering': ['-is_critical', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatusReport',
            fields=[
                ('active_status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_equipment', models.PositiveIntegerField()),
                ('working_equipment', models.PositiveIntegerField()),
                ('under_repair_equipment', models.PositiveIntegerField()),
                ('not_working_equipment', models.PositiveIntegerField()),
                ('pending_delete', models.BooleanField(default=False)),
                ('critical_equipment_total', models.PositiveIntegerField()),
                ('critical_equipment_working', models.PositiveIntegerField()),
                ('critical_equipment_under_repair', models.PositiveIntegerField()),
                ('critical_equipment_not_working', models.PositiveIntegerField()),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='MachineRepairHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('repair_count', models.PositiveIntegerField(default=0)),
                ('total_downtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_history', to='Inventory.equipment')),
                ('job_cards', models.ManyToManyField(related_name='repair_history', to='jobcard.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Machine Repair Histories',
                'ordering': ['-year', '-month'],
                'unique_together': {('equipment', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WorkshopEquipmentReport',
            fields=[
                ('active_status', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('total_equipment', models.PositiveIntegerField()),
                ('critical_equipment', models.PositiveIntegerField()),
                ('general_equipment', models.PositiveIntegerField()),
                ('pending_delete', models.BooleanField(default=False)),
                ('working_count', models.PositiveIntegerField()),
                ('under_repair_count', models.PositiveIntegerField()),
                ('not_working_count', models.PositiveIntegerField()),
                ('last_month_repairs', models.PositiveIntegerField()),
                ('last_month_calibrations', models.PositiveIntegerField()),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reports', to='workshop.workshop')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('workshop', 'report_date')},
            },
        ),
    ]
