# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for each audit event', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_index=True, help_text='Name of the table where the operation occurred', max_length=255)),
                ('row_id', models.UUIDField(db_index=True, help_text='UUID of the affected row')),
                ('operation', models.CharField(choices=[('c', 'Create'), ('u', 'Update'), ('d', 'Delete (Hard)'), ('r', 'Restore/Reactivate'), ('t', 'Transfer'), ('s', 'Soft Delete/Deactivate'), ('b', 'Broadcast (Mirror Sync)')], db_index=True, help_text='Operation type: c=Create, u=Update, d=Delete, r=Restore, t=Transfer, s=Soft Delete, b=Broadcast', max_length=1)),
                ('source', models.CharField(db_index=True, help_text='Source system/application that triggered the operation', max_length=50)),
                ('user_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of user who performed the operation (if applicable)', null=True)),
                ('changed_fields', models.JSONField(blank=True, help_text='Array of field names that were modified', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values before the operation', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values after the operation', null=True)),
                ('data', models.JSONField(blank=True, help_text='Complete row data - auto-populated from new_values or old_values', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context data (IP address, device info, etc.)', null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the audit event was received')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the audit record was created')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'audit_log',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['table_name', 'row_id', '-received_at'], name='idx_table_row'), models.Index(condition=models.Q(('operation', 'b')), fields=['table_name', 'operation'], name='idx_broadcasts')],
            },
        ),
    ]
