# Generated by Django 4.2.30 on 2026-06-02 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, help_text='Unique client identifier (derived from MAC address on first run)', max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, help_text='Hospital/workshop name from client config', max_length=255, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, help_text='Last heartbeat timestamp', null=True)),
                ('last_upload', models.DateTimeField(blank=True, help_text='Last time client pushed data to HQ', null=True)),
                ('last_download', models.DateTimeField(blank=True, help_text='Last time client pulled data from HQ', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline')], db_index=True, default='active', max_length=50)),
                ('ip_address', models.CharField(blank=True, help_text='Last known IP address of the client', max_length=50, null=True)),
                ('version', models.CharField(blank=True, help_text='Desktop app version string', max_length=50, null=True)),
                ('workshop_data', models.JSONField(blank=True, help_text='Workshop metadata pushed by the client', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this client first registered')),
            ],
            options={
                'verbose_name': 'Sync Client',
                'verbose_name_plural': 'Sync Clients',
                'db_table': 'sync_clients',
                'ordering': ['-last_seen'],
            },
        ),
    ]
