# Generated by Django 4.2.30 on 2026-06-03 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_syncclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncclient',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
