# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('users', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesManufacturer',
            fields=[
                ('name', models.CharField(max_length=150, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accessoriesname',
            fields=[
                ('name', models.CharField(max_length=150, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Toolname',
            fields=[
                ('name', models.CharField(max_length=150, unique=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolsManufacturer',
            fields=[
                ('name', models.CharField(max_length=150, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active_status', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, max_length=100, null=True)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit in KSh', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('equipment_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='Inventory.equipmentdescription')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='parts_tools.accessoriesmanufacturer')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='parts_tools.accessoriesname')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='AccessoryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('new', 'New Accessory'), ('restock', 'Restock Existing')], default='new', help_text='Type of request', max_length=20)),
                ('accessory_name', models.CharField(blank=True, help_text='Name of the new accessory', max_length=200, null=True)),
                ('manufacturer_name', models.CharField(blank=True, help_text='Manufacturer name', max_length=150, null=True)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit in KSh', max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_reason', models.TextField(blank=True, help_text='Reason for approval or decline by HOD', null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_note', models.TextField(blank=True, help_text='Note from the user who accepted the accessory', null=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('accepted_by', models.ForeignKey(blank=True, help_text='Workshop user who received/accepted the accessory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_acceptances', to='users.userprofile')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessory_approvals', to='users.userprofile')),
                ('created_accessory', models.ForeignKey(blank=True, help_text='The accessory created from this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='parts_tools.accessories')),
                ('equipment_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_requests', to='Inventory.equipmentdescription')),
                ('existing_accessory', models.ForeignKey(blank=True, help_text='Select existing accessory for restock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restock_requests', to='parts_tools.accessories')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_requests', to='users.userprofile')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_requests', to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'Accessory Request',
                'verbose_name_plural': 'Accessory Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessoryRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('declined', 'Declined'), ('accepted', 'Accepted'), ('modified', 'Modified')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_actions', to='users.userprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parts_tools.accessoryrequest')),
            ],
            options={
                'verbose_name': 'Request History',
                'verbose_name_plural': 'Request Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='parts_tools.toolname')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='parts_tools.toolsmanufacturer')),
            ],
            options={
                'verbose_name_plural': 'Tools',
            },
        ),
        migrations.AddIndex(
            model_name='accessoryrequest',
            index=models.Index(fields=['status', 'workshop'], name='parts_tools_status_909ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='accessoryrequest',
            index=models.Index(fields=['requested_by', 'status'], name='parts_tools_request_015284_idx'),
        ),
    ]
