# Generated by Django 5.2.17 on 2026-09-26 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("parts_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessories",
            name="reorder_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accessories",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accessories",
                to="assets.supplier",
            ),
        ),
    ]
