# Generated by Django 5.2.15 on 2026-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_tools', '0002_accessories_reorder_level_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='low_stock_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
