# Generated by Django 5.2.15 on 2026-09-28 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0004_work_order_checklist_selection'),
        ('parts_tools', '0003_accessory_low_stock_alerted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change', models.IntegerField(help_text='+ into stock, - out of stock')),
                ('reason', models.CharField(choices=[('opening', 'Opening balance'), ('work_order', 'Used on a work order'), ('work_order_undone', 'Work order declined: returned'), ('received', 'Received'), ('adjustment', 'Stock count corrected')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('needs_sync', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('accessory', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movements', to='parts_tools.accessories')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_movements', to='jobcard.jobcard')),
                ('request', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_movements', to='parts_tools.accessoryrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['accessory', 'reason'], name='parts_tools_accesso_9c0981_idx')],
            },
        ),
    ]
