# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('machineReports', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machineReports.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.department'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop'),
        ),
        migrations.AddField(
            model_name='equipmentdescription',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='machineReports.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.equipmentdescription'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.manufacturer'),
        ),
    ]
