# Generated by Django 5.2.15 on 2026-09-24 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('default_warranty_months', models.PositiveIntegerField(blank=True, help_text="Warranty this supplier normally gives; fills an equipment's expiry when left blank", null=True)),
                ('warranty_terms', models.TextField(blank=True, help_text='What the warranty covers and how to claim')),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text="Left blank, it is filled from purchase date + the supplier's default warranty", null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='Inventory.supplier'),
        ),
    ]
