# Generated by Django 5.2.17 on 2026-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentdescription",
            name="checklist_template",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
