# Generated by Django 5.2.15 on 2026-09-24 19:52
# Warranties move off the Equipment row into their own table (Equipment ->
# Warranty -> Supplier), so the inventory table stays about the equipment.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def equipment_warranty_to_rows(apps, schema_editor):
    """Equipment.warranty_expiry (and its supplier / purchase date) becomes a Warranty row."""
    Equipment = apps.get_model('Inventory', 'Equipment')
    Warranty = apps.get_model('Inventory', 'Warranty')
    # The database being migrated, not the router's default: the desktop also
    # runs `migrate --database=hq`, and a bare .objects query would read the
    # local database instead.
    db = schema_editor.connection.alias
    for eq in Equipment.objects.using(db).filter(warranty_expiry__isnull=False):
        start = eq.purchase_date or eq.warranty_expiry
        Warranty.objects.using(db).create(
            equipment=eq, supplier=eq.supplier, start_date=start, expiry_date=eq.warranty_expiry,
            terms=eq.supplier.warranty_terms if eq.supplier else '',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_supplier_and_equipment_warranty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_warranty_months',
            field=models.PositiveIntegerField(blank=True, help_text='Warranty period this supplier normally gives; pre-fills new warranties', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='warranty_terms',
            field=models.TextField(blank=True, help_text='Standard warranty terms; pre-fill new warranties'),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, help_text='Warranty certificate or contract number', max_length=100)),
                ('start_date', models.DateField()),
                ('period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(help_text='Left blank, it is start date + period')),
                ('coverage', models.JSONField(blank=True, default=list, help_text='Codes from COVERAGE_CHOICES')),
                ('coverage_other', models.CharField(blank=True, help_text='Anything else covered', max_length=255)),
                ('terms', models.TextField(blank=True, help_text='Terms, exclusions, how to make a claim')),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties_created', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='Inventory.equipment')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='Inventory.supplier')),
            ],
            options={
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['equipment', 'expiry_date'], name='Inventory_w_equipme_37949d_idx')],
            },
        ),
        migrations.RunPython(equipment_warranty_to_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='warranty_expiry',
        ),
    ]
