# Generated by Django 5.2.17 on 2026-09-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0004_warranty_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="expected_life_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
