# Generated by Django 5.2.15 on 2026-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_equipment_purchase_cost_expected_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='label_snapshot',
            field=models.JSONField(blank=True, db_default=models.Value({}, models.JSONField()), default=dict),
        ),
    ]
