"""Excel / PDF export views and the reports dashboard.

Split out of the original monolithic ``views.py``; behaviour unchanged.
"""
import logging
import os

from django.conf import settings
from users.control import role_required
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Count, Case, When, IntegerField
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, Alignment
from openpyxl.utils import get_column_letter

from Inventory.models import Department, Equipment, EquipmentDescription
from workshop.models import Workshop
from Inventory.equipment_pdf_generator import (
    create_equipment_pdf_response,
    generate_equipment_pdf_report,
)

logger = logging.getLogger(__name__)


@login_required
def export_equipment_to_excel(request):
    profile = request.user.userprofile
    workshop_to_export = None

    requested_workshop_id = request.GET.get('workshop')

    if profile.role == 'HOD':
        if requested_workshop_id:
            workshop_to_export = get_object_or_404(Workshop, id=requested_workshop_id)
        else:
            messages.error(request, "Please select a workshop to export from.")
            return redirect('inventory')
    else:  # Tech
        if not profile.workshop:
            messages.error(request, "Your profile is not associated with a workshop. Cannot export.")
            return redirect('inventory')
        workshop_to_export = profile.workshop
        if requested_workshop_id and int(requested_workshop_id) != workshop_to_export.id:
            messages.error(request, "Unauthorized to export from selected workshop.")
            return redirect('inventory')

    department_id = request.GET.get('department')
    filename = f"equipment_inventory_{workshop_to_export.name}.xlsx" if workshop_to_export else "equipment_inventory.xlsx"
    export_title = f"{workshop_to_export.name} Equipment Inventory" if workshop_to_export else "Equipment Inventory"

    try:
        if department_id:
            department = get_object_or_404(Department, id=department_id, workshop=workshop_to_export)
            equipments = Equipment.objects.filter(
                department=department, active_status=True
            ).select_related('department', 'description')
            filename = f"{department.name}_equipment_inventory.xlsx"
            export_title = f"{department.name} - Equipment Inventory ({workshop_to_export.name})"
        else:
            equipments = Equipment.objects.filter(
                department__workshop=workshop_to_export, active_status=True
            ).select_related('department', 'description')

    except Exception as e:
        messages.error(request, "Error fetching equipment data for export.")
        return redirect('inventory')

    if not equipments.exists():
        messages.warning(request, "No equipment found to export.")
        return redirect('inventory')

    template_path = os.path.join(settings.STATIC_ROOT, 'equipment_template.xlsx')
    if not os.path.exists(template_path):
        messages.error(request, "Excel template not found.")
        return redirect('inventory')

    try:
        wb = load_workbook(template_path)
        ws = wb.active
        ws['A1'].value = export_title
    except Exception as e:
        messages.error(request, "Error loading Excel template.")
        return redirect('inventory')

    row = 3
    for item in equipments:
        ws.cell(row=row, column=1).value = item.description.name if item.description else ""
        ws.cell(row=row, column=2).value = str(item.manufacturer) if item.manufacturer else ""
        ws.cell(row=row, column=3).value = item.model or ""
        ws.cell(row=row, column=4).value = item.serial_number or ""
        ws.cell(row=row, column=5).value = item.department.name if item.department else ""
        ws.cell(row=row, column=6).value = item.get_status_display() if hasattr(item, 'get_status_display') else str(item.status or "")

        row += 1

    user_name = request.user.first_name or request.user.username
    ws.cell(row=row, column=1).value = f"Generated by: {user_name}"
    ws.merge_cells(f'A{row}:F{row}')
    ws[f'A{row}'].font = Font(bold=True, size=12)
    ws[f'A{row}'].alignment = Alignment(horizontal='center')

    headers = ["Description", "Manufacturer", "Model", "Serial Number", "Department", "Status"]
    for col_num in range(1, len(headers) + 1):
        max_length = 0
        column_letter = get_column_letter(col_num)
        for row_num in range(2, ws.max_row + 1):
            cell = ws.cell(row=row_num, column=col_num)
            if cell.value:
                try:
                    max_length = max(max_length, len(str(cell.value)))
                except:
                    pass
            adjusted_width = max(max_length + 2, 3)
            ws.column_dimensions[column_letter].width = adjusted_width

    try:
        response = HttpResponse(
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        wb.save(response)
        return response
    except Exception as e:
        messages.error(request, "Error generating Excel file.")
        return redirect('inventory')


@login_required
def export_inventory_summary_excel(request):
    profile = request.user.userprofile
    workshop_to_export = None

    requested_workshop_id = request.GET.get('workshop')

    if profile.role == 'HOD':
        if requested_workshop_id:
            workshop_to_export = get_object_or_404(Workshop, id=requested_workshop_id)
        else:
            messages.error(request, "Please select a workshop to export summary from.")
            return redirect('inventory')
    else:  # Tech
        if not profile.workshop:
            messages.error(request, "Your profile is not associated with a workshop. Cannot export summary.")
            return redirect('inventory')
        workshop_to_export = profile.workshop
        if requested_workshop_id and int(requested_workshop_id) != workshop_to_export.id:
            messages.error(request, "Unauthorized to export summary from selected workshop.")
            return redirect('inventory')

    department_filter = request.GET.get('department', '')
    description_filter = request.GET.get('description', '')

    base_queryset = Equipment.objects.filter(department__workshop=workshop_to_export, active_status=True)
    filtered_queryset = base_queryset
    filename = f"inventory_summary_{workshop_to_export.name}.xlsx" if workshop_to_export else "inventory_summary.xlsx"

    if department_filter:
        try:
            department = get_object_or_404(Department, id=department_filter, workshop=workshop_to_export)
            filtered_queryset = filtered_queryset.filter(department=department)
            filename = f"{department.name}_inventory_summary.xlsx"
        except Department.DoesNotExist:
            pass

    if description_filter:
        try:
            description = get_object_or_404(EquipmentDescription, id=description_filter)
            filtered_queryset = filtered_queryset.filter(description=description)
            if department_filter:
                filename = f"{department.name}_{description.name}_summary.xlsx"
            else:
                filename = f"{description.name}_inventory_summary.xlsx"
        except EquipmentDescription.DoesNotExist:
            pass

    summary_data = filtered_queryset.values(
        'description__name'
    ).annotate(
        total_count=Count('id'),
        working_count=Count(
            Case(When(status='Working', then=1), output_field=IntegerField())
        ),
        not_working_count=Count(
            Case(When(status='Not working', then=1), output_field=IntegerField())
        ),
        under_repair_count=Count(
            Case(When(status='Under repair', then=1), output_field=IntegerField())
        )
    ).order_by('description__name')

    wb = Workbook()
    ws = wb.active
    ws.title = "Inventory Summary"

    headers = ['Equipment Description', 'Working', 'Not Working', 'Under Repair', 'Total']
    for col_num, header in enumerate(headers, 1):
        col_letter = get_column_letter(col_num)
        ws[f'{col_letter}1'] = header
        ws[f'{col_letter}1'].font = Font(bold=True)
        ws[f'{col_letter}1'].alignment = Alignment(horizontal='center')

    row_num = 2
    total_working = 0
    total_not_working = 0
    total_under_repair = 0
    total_equipment = 0

    for item in summary_data:
        ws[f'A{row_num}'] = item['description__name']
        ws[f'B{row_num}'] = item['working_count']
        ws[f'C{row_num}'] = item['not_working_count']
        ws[f'D{row_num}'] = item['under_repair_count']
        ws[f'E{row_num}'] = item['total_count']

        total_working += item['working_count']
        total_not_working += item['not_working_count']
        total_under_repair += item['under_repair_count']
        total_equipment += item['total_count']

        row_num += 1

    ws[f'A{row_num}'] = "TOTAL"
    ws[f'B{row_num}'] = total_working
    ws[f'C{row_num}'] = total_not_working
    ws[f'D{row_num}'] = total_under_repair
    ws[f'E{row_num}'] = total_equipment

    for col in range(1, 6):
        col_letter = get_column_letter(col)
        ws[f'{col_letter}{row_num}'].font = Font(bold=True)

    for col in ws.columns:
        max_length = 0
        column = col[0].column_letter
        for cell in col:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = (max_length + 2) * 1.2
        ws.column_dimensions[column].width = adjusted_width

    row_num += 2
    user_name = request.user.first_name or request.user.username
    ws[f'A{row_num}'] = f"Generated by: {user_name}"
    ws[f'A{row_num}'].font = Font(bold=True)

    response = HttpResponse(
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    wb.save(response)

    return response


@login_required
def export_equipment_to_pdf(request):
    profile = request.user.userprofile
    workshop_to_export = None

    # Determine workshop
    requested_workshop_id = request.GET.get('workshop')
    if profile.role == 'HOD':
        if requested_workshop_id:
            workshop_to_export = get_object_or_404(Workshop, id=requested_workshop_id)
        else:
            messages.error(request, "Please select a workshop to export from.")
            return redirect('inventory')
    else:
        if not profile.workshop:
            messages.error(request, "Your profile is not associated with a workshop.")
            return redirect('inventory')
        workshop_to_export = profile.workshop
        # ✅ FIX: Compare UUID strings directly, don't convert to int
        if requested_workshop_id and str(requested_workshop_id) != str(workshop_to_export.id):
            messages.error(request, "Unauthorized to export from selected workshop.")
            return redirect('inventory')

    # --- Apply same filters as inventory view ---
    equipments = Equipment.objects.filter(
        department__workshop=workshop_to_export,
        active_status=True
    ).select_related('department', 'description', 'manufacturer')

    department_filter = request.GET.get('department', '').strip()
    search_query = request.GET.get('search', '').strip()
    status_filter = request.GET.get('status', '').strip()

    current_department = None
    if department_filter:
        try:
            current_department = Department.objects.get(id=department_filter, workshop=workshop_to_export)
            equipments = equipments.filter(department=current_department)
        except Department.DoesNotExist:
            pass

    if search_query:
        equipments = equipments.filter(
            Q(description__name__icontains=search_query) |
            Q(manufacturer__name__icontains=search_query) |
            Q(model__icontains=search_query) |
            Q(serial_number__icontains=search_query) |
            Q(department__name__icontains=search_query)
        )

    if status_filter and status_filter in ['Working', 'Not working', 'Under repair']:
        equipments = equipments.filter(status=status_filter)

    # --- If no results ---
    if not equipments.exists():
        messages.warning(request, "No equipment found to export.")
        return redirect('inventory')

    # --- Build context ---
    context = {
        'workshop': workshop_to_export,
        'department': current_department,
        'status_filter': status_filter,
        'total_equipment': equipments.count(),
        'generated_by': f"{request.user.first_name} {request.user.last_name}".strip() or request.user.username,
        'notes': request.GET.get('notes', ''),
    }

    # --- Generate PDF ---
    try:
        return create_equipment_pdf_response(
            workshop_to_export,
            equipments,
            request.GET.get('report_type', 'detailed'),
            context,
            request
        )
    except Exception as e:
        logger.error(f"PDF generation failed: {str(e)}")
        messages.error(request, "Failed to generate PDF report. Please try again.")
        return redirect('inventory')


@login_required
def export_inventory_summary_to_pdf(request):
    """Export inventory summary to PDF format"""
    profile = request.user.userprofile
    workshop_to_export = None

    # Workshop selection logic (same as existing summary export)
    requested_workshop_id = request.GET.get('workshop')

    if profile.role == 'HOD':
        if requested_workshop_id:
            workshop_to_export = get_object_or_404(Workshop, id=requested_workshop_id)
        else:
            messages.error(request, "Please select a workshop to export summary from.")
            return redirect('inventory')
    else:  # Tech
        if not profile.workshop:
            messages.error(request, "Your profile is not associated with a workshop. Cannot export summary.")
            return redirect('inventory')
        workshop_to_export = profile.workshop
        if requested_workshop_id and int(requested_workshop_id) != workshop_to_export.id:
            messages.error(request, "Unauthorized to export summary from selected workshop.")
            return redirect('inventory')

    # Get filters
    department_filter = request.GET.get('department', '')
    description_filter = request.GET.get('description', '')

    # Build queryset with filters
    base_queryset = Equipment.objects.filter(department__workshop=workshop_to_export, active_status=True)
    filtered_queryset = base_queryset

    current_department = None
    current_description = None

    if department_filter:
        try:
            current_department = get_object_or_404(Department, id=department_filter, workshop=workshop_to_export)
            filtered_queryset = filtered_queryset.filter(department=current_department)
        except Department.DoesNotExist:
            pass

    if description_filter:
        try:
            current_description = get_object_or_404(EquipmentDescription, id=description_filter)
            filtered_queryset = filtered_queryset.filter(description=current_description)
        except EquipmentDescription.DoesNotExist:
            pass

    if not filtered_queryset.exists():
        messages.warning(request, "No equipment found matching the selected criteria.")
        return redirect('inventory')

    # Prepare context
    context = {
        'workshop': workshop_to_export,
        'department': current_department,
        'description': current_description,
        'generated_by': f"{request.user.first_name} {request.user.last_name}".strip() or request.user.username,
    }

    # Generate PDF using summary report type
    try:
        return create_equipment_pdf_response(
            workshop_to_export,
            filtered_queryset,
            'summary',
            context,
            request
        )
    except Exception as e:
        logger.error(f"Summary PDF generation failed: {str(e)}")
        messages.error(request, "Failed to generate summary PDF report. Please try again.")
        return redirect('inventory')


@login_required
@role_required('HOD', redirect_to='inventory', message="Only Heads of Department can perform bulk exports.")
def bulk_export_departments_pdf(request):
    """Generate separate PDF reports for each department in a workshop"""
    profile = request.user.userprofile


    workshop_id = request.GET.get('workshop')
    if not workshop_id:
        messages.error(request, "Please select a workshop for bulk export.")
        return redirect('inventory')

    try:
        workshop = get_object_or_404(Workshop, id=workshop_id)
        departments = Department.objects.filter(workshop=workshop).order_by('name')

        if not departments.exists():
            messages.warning(request, f"No departments found in {workshop.name}.")
            return redirect('inventory')

        # Create a ZIP file containing multiple PDFs
        import zipfile
        from django.http import HttpResponse
        import tempfile

        # Create temporary file for ZIP
        with tempfile.NamedTemporaryFile(delete=False) as tmp_zip:
            with zipfile.ZipFile(tmp_zip, 'w', zipfile.ZIP_DEFLATED) as zip_file:

                for department in departments:
                    equipment_queryset = Equipment.objects.filter(
                        department=department, active_status=True
                    ).select_related('description', 'manufacturer')

                    if equipment_queryset.exists():
                        # Generate PDF for this department
                        context = {
                            'workshop': workshop,
                            'department': department,
                            'generated_by': f"{request.user.first_name} {request.user.last_name}".strip() or request.user.username,
                        }

                        pdf_buffer = generate_equipment_pdf_report(
                            workshop, equipment_queryset, 'detailed', context
                        )

                        # Add to ZIP
                        filename = f"{department.name.replace(' ', '_')}_equipment_report.pdf"
                        zip_file.writestr(filename, pdf_buffer.getvalue())
                        pdf_buffer.close()

            # Prepare response
            tmp_zip.seek(0)
            response = HttpResponse(tmp_zip.read(), content_type='application/zip')
            response['Content-Disposition'] = f'attachment; filename="{workshop.name.replace(" ", "_")}_all_departments_reports.zip"'

            # Clean up
            import os
            os.unlink(tmp_zip.name)

            return response

    except Exception as e:
        logger.error(f"Bulk PDF export failed: {str(e)}")
        messages.error(request, "Failed to generate bulk PDF reports. Please try again.")
        return redirect('inventory')
