# Generated by Django 6.0.1 on 2026-01-18 20:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('calibration_center', 'Calibration Center'), ('maintenance', 'Maintenance')], default='maintenance', max_length=50)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_workshop_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pending_delete', 'updated_at'], name='workshop_wo_pending_574cf6_idx'), models.Index(fields=['needs_sync'], name='workshop_wo_needs_s_d0769e_idx'), models.Index(fields=['updated_at'], name='workshop_wo_updated_ec8518_idx')],
            },
        ),
    ]
