# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CalSoft', '0001_initial'),
        ('Inventory', '0001_initial'),
        ('calSchedules', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationnotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationprocedure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationparameter',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='CalSoft.calibrationprocedure'),
        ),
        migrations.AddField(
            model_name='calibrationreading',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalSoft.calibrationparameter'),
        ),
        migrations.AddField(
            model_name='calibrationreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationschedule',
            name='calibration_procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='CalSoft.calibrationprocedure'),
        ),
        migrations.AddField(
            model_name='calibrationschedule',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_schedules', to='Inventory.equipment'),
        ),
        migrations.AddField(
            model_name='calibrationschedule',
            name='workshop',
            field=models.ForeignKey(help_text='Workshop managing this calibration schedule', on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_schedules', to='workshop.workshop'),
        ),
        migrations.AddField(
            model_name='calibrationauditlog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='CalSoft.calibrationschedule'),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.department'),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='device_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.equipmentdescription'),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='device_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='CalSoft.calibrationprocedure'),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='calSchedules.calibrationschedule'),
        ),
        migrations.AddField(
            model_name='calibrationschedule',
            name='calibration_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='CalSoft.calibrationsession'),
        ),
        migrations.AddField(
            model_name='calibrationreport',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='CalSoft.calibrationsession'),
        ),
        migrations.AddField(
            model_name='calibrationreading',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='CalSoft.calibrationsession'),
        ),
        migrations.AddField(
            model_name='calibrationworkflow',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calsoft_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationworkflow',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='CalSoft.calibrationschedule'),
        ),
        migrations.AddField(
            model_name='equipmentcalibrationprocedure',
            name='calibration_procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_mappings', to='CalSoft.calibrationprocedure'),
        ),
        migrations.AddField(
            model_name='equipmentcalibrationprocedure',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_equipment_procedure_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentcalibrationprocedure',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calsoft_procedure_mappings', to='Inventory.equipment'),
        ),
        migrations.AddIndex(
            model_name='historicalcalibration',
            index=models.Index(fields=['device_serial', 'parameter_name', 'sub_parameter_name'], name='CalSoft_his_device__99036a_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalcalibration',
            index=models.Index(fields=['calibration_date'], name='CalSoft_his_calibra_2b333f_idx'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CalSoft.parametercategory'),
        ),
        migrations.AddField(
            model_name='pendingcertificate',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_certificate', to='CalSoft.calibrationsession'),
        ),
        migrations.AddField(
            model_name='sessionparameterresolution',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalSoft.calibrationparameter'),
        ),
        migrations.AddField(
            model_name='sessionparameterresolution',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_resolutions', to='CalSoft.calibrationsession'),
        ),
        migrations.AddField(
            model_name='setvalue',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_values', to='CalSoft.calibrationparameter'),
        ),
        migrations.AddField(
            model_name='calibrationreading',
            name='set_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalSoft.setvalue'),
        ),
        migrations.AddField(
            model_name='standard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentcalibrationprocedure',
            name='required_standards',
            field=models.ManyToManyField(blank=True, to='CalSoft.standard'),
        ),
        migrations.AddField(
            model_name='standardparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalSoft.parameter'),
        ),
        migrations.AddField(
            model_name='standardparameter',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CalSoft.standard'),
        ),
        migrations.AddField(
            model_name='standardtype',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='CalSoft.parameter'),
        ),
        migrations.AddField(
            model_name='subparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_parameters', to='CalSoft.calibrationparameter'),
        ),
        migrations.AddField(
            model_name='setvalue',
            name='sub_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_values', to='CalSoft.subparameter'),
        ),
        migrations.AddField(
            model_name='calibrationreading',
            name='sub_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CalSoft.subparameter'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['workshop', 'scheduled_month'], name='CalSoft_cal_worksho_818831_idx'),
        ),
        migrations.AddIndex(
            model_name='calibrationschedule',
            index=models.Index(fields=['equipment', 'status'], name='CalSoft_cal_equipme_4fc3bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calibrationschedule',
            unique_together={('equipment', 'scheduled_month')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionparameterresolution',
            unique_together={('session', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='standardparameter',
            unique_together={('standard', 'parameter')},
        ),
        migrations.AlterUniqueTogether(
            name='calibrationreading',
            unique_together={('session', 'parameter', 'sub_parameter', 'set_value')},
        ),
    ]
