# Generated by Django 4.2.30 on 2026-06-04 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CalSoft', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='rejection_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationsession',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('data_quality', 'Data Quality Issues'), ('procedure_not_followed', 'Procedure Not Followed'), ('equipment_error', 'Equipment Error'), ('environmental_conditions', 'Environmental Conditions'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
