# Generated by Django 4.2.30 on 2026-06-04 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_initial'),
        ('CalSoft', '0003_calibrationsession_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationauditlog',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='Inventory.equipment'),
        ),
        migrations.AddField(
            model_name='calibrationauditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='CalSoft.calibrationsession'),
        ),
    ]
