# Generated by Django 4.2.30 on 2026-06-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calSchedules', '0003_alter_calibrationschedule_status'),
        ('CalSoft', '0004_calibrationauditlog_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationauditlog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calsoft_audit_logs', to='calSchedules.calibrationschedule'),
        ),
    ]
