# Generated by Django 5.2.17 on 2026-09-26 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0005_alter_calibrationauditlog_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationparameter",
            name="num_readings",
            field=models.PositiveIntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(3),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
