# Generated by Django 5.2.17 on 2026-09-26 22:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0006_alter_calibrationparameter_num_readings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="issued_certificates/%Y/%m/")),
                ("sha256", models.CharField(max_length=64)),
                ("size", models.PositiveIntegerField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_certificates",
                        to="CalSoft.calibrationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "certificate_number"),
                        name="issued_certificate_once",
                    )
                ],
            },
        ),
    ]
