# Generated by Django 5.2.17 on 2026-09-26 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0007_issuedcertificate"),
        ("calSchedules", "0003_alter_calibrationschedule_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationworkflow",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_steps",
                to="calSchedules.calibrationschedule",
            ),
        ),
        migrations.DeleteModel(
            name="CalibrationSchedule",
        ),
    ]
