# Generated by Django 5.2.17 on 2026-09-27 20:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0008_alter_calibrationworkflow_schedule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnsurSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Show the Start with Ansur button on Perform Calibration.",
                    ),
                ),
                ("program_path", models.CharField(blank=True, max_length=500)),
                (
                    "base_folder",
                    models.CharField(default="C:\\CirqenAnsur", max_length=500),
                ),
                (
                    "delete_job_files",
                    models.BooleanField(
                        default=True,
                        help_text="Remove the work-order file once its result is imported.",
                    ),
                ),
                (
                    "archive_years",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnsurTemplateMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("template_file", models.CharField(max_length=255)),
                (
                    "ansur_standard",
                    models.CharField(
                        blank=True,
                        help_text="Safety standard in Ansur, e.g. IEC 62353.",
                        max_length=100,
                    ),
                ),
                ("service_event", models.CharField(default="PM", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansur_template",
                        to="CalSoft.calibrationprocedure",
                    ),
                ),
            ],
            options={
                "ordering": ["procedure__name"],
            },
        ),
    ]
