# Generated by Django 5.2.17 on 2026-09-27 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0009_ansur_connection"),
        ("Inventory", "0005_equipment_purchase_cost_expected_life"),
        ("calSchedules", "0006_calibrationschedule_calschedules_one_open_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ansursettings",
            name="launch_arguments",
            field=models.CharField(default='"{job}"', max_length=300),
        ),
        migrations.AddField(
            model_name="ansursettings",
            name="pdf_arguments",
            field=models.CharField(default='/f "{record}" /h', max_length=300),
        ),
        migrations.AddField(
            model_name="calibrationparameter",
            name="analyser_accuracy_floor",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="± fixed part, in the parameter's unit",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calibrationparameter",
            name="analyser_accuracy_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="± % of reading",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="calibrationparameter",
            name="analyser_resolution",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="calibrationparameter",
            name="ansur_step",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="calibrationparameter",
            name="limit_type",
            field=models.CharField(
                choices=[
                    ("two_sided", "Set value ± tolerance"),
                    ("upper", "At most the set value"),
                    ("lower", "At least the set value"),
                ],
                default="two_sided",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="calibrationreading",
            name="ansur_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="calibrationsession",
            name="ansur_disagreements",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="calibrationsession",
            name="ansur_operator",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="calibrationsession",
            name="ansur_record_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="calibrationsession",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual entry"), ("ansur", "Fluke Ansur")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AnsurJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_number", models.CharField(max_length=30, unique=True)),
                ("template_file", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("sent", "Sent to Ansur"),
                            ("imported", "Awaiting approval"),
                            ("rejected", "Record refused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="prepared",
                        max_length=12,
                    ),
                ),
                (
                    "actual_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "actual_pressure",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("job_file", models.CharField(blank=True, max_length=500)),
                ("record_copy", models.FileField(blank=True, upload_to="ansur/%Y/%m/")),
                ("record_sha256", models.CharField(blank=True, max_length=64)),
                ("pdf_copy", models.FileField(blank=True, upload_to="ansur/%Y/%m/")),
                ("pdf_sha256", models.CharField(blank=True, max_length=64)),
                ("error", models.TextField(blank=True)),
                ("warning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansur_jobs",
                        to="Inventory.equipment",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="CalSoft.calibrationprocedure",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="calSchedules.calibrationschedule",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ansur_job",
                        to="CalSoft.calibrationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ["prepared", "sent", "rejected"])
                        ),
                        fields=("equipment",),
                        name="ansur_one_open_job_per_equipment",
                    )
                ],
            },
        ),
    ]
