# Generated by Django 5.2.17 on 2026-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CalSoft", "0010_ansur_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="calibrationsession",
            name="ansur_checks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
