# Generated by Django 5.2.15 on 2026-09-28 09:22

from django.db import migrations, models


def copy_job_numbers(apps, schema_editor):
    """Ansur sessions imported before this migration get their job number."""
    AnsurJob = apps.get_model("CalSoft", "AnsurJob")
    CalibrationSession = apps.get_model("CalSoft", "CalibrationSession")
    for job in AnsurJob.objects.exclude(session=None).only("session_id", "job_number"):
        CalibrationSession.objects.filter(pk=job.session_id).update(ansur_job_number=job.job_number)


class Migration(migrations.Migration):

    dependencies = [
        ('CalSoft', '0011_ansur_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationsession',
            name='ansur_job_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='calibrationparameter',
            name='ansur_step',
            field=models.CharField(blank=True, db_default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='calibrationparameter',
            name='limit_type',
            field=models.CharField(choices=[('two_sided', 'Set value ± tolerance'), ('upper', 'At most the set value'), ('lower', 'At least the set value')], db_default='two_sided', default='two_sided', max_length=12),
        ),
        migrations.AlterField(
            model_name='calibrationreading',
            name='ansur_status',
            field=models.CharField(blank=True, db_default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='calibrationsession',
            name='ansur_checks',
            field=models.JSONField(blank=True, db_default=models.Value([], models.JSONField()), default=list),
        ),
        migrations.AlterField(
            model_name='calibrationsession',
            name='ansur_disagreements',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='calibrationsession',
            name='ansur_operator',
            field=models.CharField(blank=True, db_default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='calibrationsession',
            name='ansur_record_sha256',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='calibrationsession',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual entry'), ('ansur', 'Fluke Ansur')], db_default='manual', default='manual', max_length=10),
        ),
        migrations.RunPython(copy_job_numbers, migrations.RunPython.noop),
    ]
