# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_version', models.CharField(default='0.0.0', max_length=50)),
                ('changes', models.TextField(blank=True)),
                ('critical', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('package_path', models.CharField(max_length=500)),
                ('manifest_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Update Package',
                'verbose_name_plural': 'Update Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_check_enabled', models.BooleanField(default=True)),
                ('check_interval_hours', models.IntegerField(default=24)),
                ('auto_apply_updates', models.BooleanField(default=False)),
                ('auto_apply_critical', models.BooleanField(default=True)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('update_templates', models.BooleanField(default=True)),
                ('update_static', models.BooleanField(default=True)),
                ('update_django_apps', models.BooleanField(default=True)),
                ('update_python_code', models.BooleanField(default=True)),
                ('update_migrations', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Update Settings',
                'verbose_name_plural': 'Update Settings',
            },
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('applying', 'Applying'), ('success', 'Success'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('backup_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('auto_applied', models.BooleanField(default=False)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='updates.updatepackage')),
            ],
            options={
                'verbose_name': 'Update History',
                'verbose_name_plural': 'Update History',
                'ordering': ['-started_at'],
            },
        ),
    ]
