"""The version numbers that decide whether a release reaches the fleet.

Two files have to agree, and when they do not the failure is silent:

  Equiper/settings.py APP_VERSION   what a desktop reports as its own version
  hq_server/version.txt             what the update server builds a package for

A desktop asks the update server for anything newer than APP_VERSION. If
APP_VERSION has moved ahead of hq_server/version.txt, the server's newest
package is not newer, every desktop is told "no update available", and the
release simply never lands — with nothing anywhere reporting an error.

version.txt at the repo root is generated from APP_VERSION by
build.py stamp_version_txt(), and render.yaml's APP_VERSION is only a fallback
for a missing version.txt, but both are checked here because drift in either
is what makes a release look deployed when it is not.
"""
import re
from pathlib import Path

from django.conf import settings
from django.test import SimpleTestCase

REPO = Path(settings.BASE_DIR)
SEMVER = re.compile(r"^\d+\.\d+\.\d+$")


def _version_tuple(value: str) -> tuple:
    return tuple(int(part) for part in value.split("."))


class VersionConsistencyTests(SimpleTestCase):
    def setUp(self):
        self.app_version = settings.APP_VERSION
        self.package_version = (REPO / "hq_server" / "version.txt").read_text().strip()

    def test_app_version_is_a_semantic_version(self):
        self.assertRegex(self.app_version, SEMVER)

    def test_the_update_server_builds_the_version_desktops_expect(self):
        self.assertEqual(
            self.package_version, self.app_version,
            "hq_server/version.txt and settings.APP_VERSION disagree. The update "
            "server builds a package for the first; desktops report the second and "
            "are told 'no update' unless the server's version is higher. Bump both.",
        )

    def test_neither_direction_of_drift(self):
        """Both directions break the fleet, in different ways.

        APP_VERSION ahead of the package version: every desktop reports a
        version the server cannot beat, so no release is ever offered and the
        fleet is stuck.

        Package version ahead of APP_VERSION: the package is built from this
        repo, so it CONTAINS the lower APP_VERSION. A desktop applies it, still
        reports the old version, is offered the same package again, and applies
        it forever — download, backup, migrate, health check and restart on a
        loop, on every machine.
        """
        app, package = _version_tuple(self.app_version), _version_tuple(self.package_version)
        if app > package:
            self.fail(
                f"APP_VERSION {self.app_version} is ahead of hq_server/version.txt "
                f"{self.package_version}: no release will ever be offered."
            )
        if package > app:
            self.fail(
                f"hq_server/version.txt {self.package_version} is ahead of APP_VERSION "
                f"{self.app_version}: the package carries the older APP_VERSION, so "
                f"desktops re-apply it on every check — an endless update loop."
            )

    def test_root_version_txt_matches(self):
        """Generated by build.py from APP_VERSION; drift means a stale build."""
        root_version = (REPO / "version.txt").read_text().strip()
        self.assertEqual(
            root_version, self.app_version,
            "version.txt is stamped from settings.APP_VERSION by build.py; "
            "they disagree, so this tree was not built from its own settings.",
        )

    def test_render_yaml_fallback_matches(self):
        """Only used when version.txt is missing, but a stale value here is how
        a deploy quietly builds the wrong package."""
        render_yaml = (REPO / "hq_server" / "render.yaml").read_text()
        match = re.search(r"key:\s*APP_VERSION\s*\n\s*value:\s*\"([^\"]+)\"", render_yaml)
        self.assertIsNotNone(match, "APP_VERSION not found in hq_server/render.yaml")
        self.assertEqual(
            match.group(1), self.app_version,
            "render.yaml's APP_VERSION fallback is stale relative to APP_VERSION.",
        )
