# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('parts_tools', '0001_initial'),
        ('ppms', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobcard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=20)),
                ('action_taken', models.CharField(choices=[('PPM', 'PPM'), ('Calibration', 'Calibration'), ('Repair', 'Repair'), ('Others', 'Others')], max_length=50)),
                ('job_description', models.TextField()),
                ('time_started', models.TimeField(blank=True, null=True)),
                ('time_completed', models.TimeField(blank=True, null=True)),
                ('technician_signed_date', models.DateTimeField(blank=True, null=True)),
                ('tech_signature', models.TextField(blank=True, help_text='Technician signature data (base64 encoded image)', null=True)),
                ('verified_signature', models.TextField(blank=True, help_text='Nurse signature data (base64 encoded image)', null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('nurse_signed_date', models.DateTimeField(blank=True, null=True)),
                ('nurse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Waiting Approval', 'Waiting Approval'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Waiting Approval', max_length=20)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('stock_deducted', models.BooleanField(default=False, help_text='Whether stock has been deducted for this job card')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of labor for this job', max_digits=10)),
                ('total_parts_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of all spare parts used (auto-calculated)', max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0.0, help_text='Any additional costs (travel, external services, etc.)', max_digits=10)),
                ('additional_costs_description', models.TextField(blank=True, help_text='Description of additional costs', null=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.department')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.equipment')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobcards', to=settings.AUTH_USER_MODEL)),
                ('related_ppm_schedule', models.ForeignKey(blank=True, help_text='Link to PPM schedule if this job card is for scheduled preventive maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='ppms.ppmschedule')),
                ('verified_by_nurse', models.ForeignKey(blank=True, help_text='The nurse who verified/approved this job card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_jobcards', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(help_text="Workshop that performed this job (may differ from department's workshop for calibration centers)", on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'verbose_name': 'Job Card',
                'verbose_name_plural': 'Job Cards',
                'ordering': ['-nurse_signed_date', '-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='SparePartUsed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit at time of use', max_digits=10)),
                ('original_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='jobcard.jobcard')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts_tools.accessories')),
            ],
            options={
                'verbose_name': 'Spare Part Used',
                'verbose_name_plural': 'Spare Parts Used',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['status', 'date_issued'], name='jobcard_job_status_e190bb_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['equipment', 'status'], name='jobcard_job_equipme_e6d686_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['department', 'status'], name='jobcard_job_departm_ee5855_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['related_ppm_schedule'], name='jobcard_job_related_0fcf80_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartused',
            index=models.Index(fields=['job_card', 'part'], name='jobcard_spa_job_car_87b2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepartused',
            index=models.Index(fields=['part', 'created_at'], name='jobcard_spa_part_id_4ef688_idx'),
        ),
    ]
