# Generated by Django 5.2.15 on 2026-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-nurse_signed_date', '-date_issued'], 'verbose_name': 'Work Order', 'verbose_name_plural': 'Work Orders'},
        ),
        migrations.AddField(
            model_name='jobcard',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
