# Generated by Django 5.2.15 on 2026-09-24 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_supplier_and_equipment_warranty'),
        ('jobcard', '0002_remarks_and_work_order_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('Any', 'Any task'), ('PPM', 'PPM'), ('Calibration', 'Calibration'), ('Repair', 'Repair'), ('Others', 'Others')], default='Any', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Overview: safety notes, tools needed, how to prepare the device')),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to=settings.AUTH_USER_MODEL)),
                ('equipment_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='Inventory.equipmentdescription')),
            ],
            options={
                'ordering': ['equipment_description__name', 'task_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.CharField(help_text="The step, e.g. 'Inspect power cord'", max_length=255)),
                ('guidance', models.TextField(blank=True, help_text='How to perform the step')),
                ('expected_result', models.CharField(blank=True, help_text="What a good result looks like, e.g. '12 V ± 0.5 V'", max_length=255)),
                ('response_type', models.CharField(choices=[('check', 'Done / Not done'), ('pass_fail', 'Pass / Fail'), ('value', 'Reading or value')], default='check', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobcard.checklisttemplate')),
            ],
            options={
                'ordering': ['template', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderChecklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('task', models.CharField(max_length=255)),
                ('guidance', models.TextField(blank=True)),
                ('expected_result', models.CharField(blank=True, max_length=255)),
                ('response_type', models.CharField(choices=[('check', 'Done / Not done'), ('pass_fail', 'Pass / Fail'), ('value', 'Reading or value')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, choices=[('done', 'Done'), ('not_done', 'Not done'), ('pass', 'Pass'), ('fail', 'Fail'), ('na', 'N/A')], max_length=10)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='jobcard.checklistitem')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_entries', to='jobcard.jobcard')),
            ],
            options={
                'verbose_name_plural': 'Work order checklist entries',
                'ordering': ['job_card', 'template_title', 'order'],
            },
        ),
    ]
