# Generated by Django 5.2.17 on 2026-09-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobcard", "0002_remarks_and_work_order_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="checklist",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
