# Generated by Django 5.2.15 on 2026-09-24 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_entries(apps, schema_editor):
    """Entries saved before this migration: link their checklist and record the
    work order's technician and sign-off time as who completed them and when."""
    Entry = apps.get_model('jobcard', 'WorkOrderChecklistEntry')
    # The database being migrated, not the router's default: the desktop also
    # runs `migrate --database=hq`, and a bare .objects query would read the
    # local database instead.
    db = schema_editor.connection.alias
    for entry in Entry.objects.using(db).select_related('item', 'job_card'):
        entry.template_id = entry.item.template_id if entry.item_id else None
        entry.completed_by_id = entry.job_card.performed_by_id
        entry.completed_at = entry.job_card.technician_signed_date or entry.created_at
        entry.save(update_fields=['template', 'completed_by', 'completed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_warranty_module'),
        ('jobcard', '0003_checklists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderchecklistentry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderchecklistentry',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_entries_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderchecklistentry',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='jobcard.checklisttemplate'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='equipment_description',
            field=models.ForeignKey(blank=True, help_text='Blank = applies to all equipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='Inventory.equipmentdescription'),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='instructions',
            field=models.TextField(blank=True, help_text='Description: purpose, safety notes, tools needed, how to prepare the device'),
        ),
        migrations.RunPython(backfill_entries, migrations.RunPython.noop),
    ]
