# Generated by Django 6.0.1 on 2026-01-18 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('workshop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppms_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PPMSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_month', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('pushed', 'Pushed')], default='pending', max_length=10)),
                ('planning_logic', models.CharField(blank=True, choices=[('description_based', 'Description Based'), ('date_based', 'Date Based')], help_text='Logic used to plan this schedule (e.g., description-based)', max_length=50, null=True)),
                ('maintenance_period', models.PositiveIntegerField(blank=True, help_text='Maintenance interval in months', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pending_delete', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
                ('needs_sync', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.equipment')),
                ('workshop', models.ForeignKey(help_text='Workshop managing this schedule', on_delete=django.db.models.deletion.CASCADE, to='workshop.workshop')),
            ],
            options={
                'indexes': [models.Index(fields=['workshop', 'scheduled_month'], name='ppms_ppmsch_worksho_b476dd_idx'), models.Index(fields=['equipment', 'status'], name='ppms_ppmsch_equipme_9aada3_idx')],
                'unique_together': {('equipment', 'scheduled_month')},
            },
        ),
    ]
