# Generated by Django 4.2.30 on 2026-05-22 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmschedule',
            name='expected_maintenance_date',
            field=models.DateField(blank=True, help_text='Expected maintenance date calculated from parent completion (for signal-created schedules)', null=True),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='generation_source',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('normalization', 'Created by Normalization'), ('signal', 'Auto-created after Completion'), ('initialization', 'Initial System Setup'), ('bulk_import', 'Bulk Import'), ('auto_advance', 'Auto-Advanced (Group-Aware)'), ('reconciliation', 'Created by Reconciliation'), ('group_alignment', 'Aligned to Group Month'), ('group_fix', 'Fixed Group Alignment'), ('locker', 'Created by Locker'), ('job_card', 'Triggered by Job Card Completion')], db_index=True, default='manual', help_text='How this schedule was created — signal-created schedules are protected from normalization', max_length=20),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='generation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this schedule was generated/created'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this schedule cannot be modified by normalization or bulk operations'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='logic_change_warning',
            field=models.TextField(blank=True, default='', help_text='Warning message set when planning_logic changes on an existing schedule. Cleared once the schedule is re-normalized under the new logic.'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, help_text='The completed schedule that triggered auto-creation of this schedule (for signal-created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_schedules', to='ppms.ppmschedule'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='previous_planning_logic',
            field=models.CharField(blank=True, default='', help_text='The planning logic that was in use before the last logic change (for smart reorganizer)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ppmschedule',
            name='planning_logic',
            field=models.CharField(blank=True, choices=[('description_based', 'Description Based'), ('date_based', 'Date Based'), ('department', 'Date Based (Department)'), ('description', 'Description Based (Alias)')], help_text='Logic used to plan this schedule (e.g., description-based)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='ppmschedule',
            index=models.Index(fields=['generation_source', 'status'], name='ppms_ppmsch_generat_c61cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='ppmschedule',
            index=models.Index(fields=['is_locked'], name='ppms_ppmsch_is_lock_ac13f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ppmschedule',
            index=models.Index(fields=['scheduled_month', 'status'], name='ppms_ppmsch_schedul_f83caa_idx'),
        ),
    ]
