# Generated by Django 5.2.15 on 2026-09-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppms', '0002_ppmschedule_expected_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmschedule',
            name='completed_date',
            field=models.DateField(blank=True, help_text='The day the maintenance was actually done (scheduled_month is when it was due)', null=True),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='due_month',
            field=models.DateField(blank=True, help_text='The month this schedule is due in its cycle. A manual push moves scheduled_month but not this, so the cycle continues from the slot.', null=True),
        ),
    ]
