# Generated by Django 5.2.15 on 2026-09-25 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppms', '0003_ppmschedule_completed_date_ppmschedule_due_month'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppmschedule',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='The plan version that placed this schedule (blank: legacy scheduler)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_schedules', to='scheduling.schedulingplan'),
        ),
        migrations.AddField(
            model_name='ppmschedule',
            name='schedule_reason',
            field=models.JSONField(blank=True, help_text='Why this month: group, months, interval, previous schedule, rule applied', null=True),
        ),
        migrations.AlterField(
            model_name='ppmschedule',
            name='generation_source',
            field=models.CharField(choices=[('manual', 'Manual Creation'), ('normalization', 'Created by Normalization'), ('signal', 'Auto-created after Completion'), ('initialization', 'Initial System Setup'), ('bulk_import', 'Bulk Import'), ('auto_advance', 'Auto-Advanced (Group-Aware)'), ('reconciliation', 'Created by Reconciliation'), ('group_alignment', 'Aligned to Group Month'), ('group_fix', 'Fixed Group Alignment'), ('locker', 'Created by Locker'), ('job_card', 'Triggered by Job Card Completion'), ('plan', 'Scheduling Plan')], db_index=True, default='manual', help_text='How this schedule was created — signal-created schedules are protected from normalization', max_length=20),
        ),
    ]
