# Generated by Django 5.2.15 on 2026-09-25 15:30

from django.db import migrations, models


def retire_surplus_open(apps, schema_editor, app_label, model_name):
    """Before the index: keep one open schedule per equipment, retire the rest.

    Same keeper rule as HQ and the sync agent (work under way, then the
    earliest month, then the lowest id). Retire, never delete; completed
    schedules are not touched. On a clean database this does nothing.
    """
    from django.db.models import Count
    from django.utils import timezone

    from sync.open_schedule_rule import keeper_key

    model = apps.get_model(app_label, model_name)
    # The database being migrated, not the router's default: the desktop also
    # runs `migrate --database=hq`.
    db = schema_editor.connection.alias
    open_qs = model.objects.using(db).filter(active_status=True, pending_delete=False).exclude(status="completed")
    crowded = list(open_qs.values("equipment_id").annotate(n=Count("id")).filter(n__gt=1)
                   .values_list("equipment_id", flat=True))
    groups = {}
    for row in open_qs.filter(equipment_id__in=crowded).values("id", "equipment_id", "status", "scheduled_month"):
        groups.setdefault(row["equipment_id"], []).append(row)
    surplus = []
    for rows in groups.values():
        rows.sort(key=lambda r: keeper_key(r["status"], r["scheduled_month"], r["id"]))
        surplus += [r["id"] for r in rows[1:]]
    if surplus:
        model.objects.using(db).filter(id__in=surplus).update(active_status=False, updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('ppms', '0004_ppmschedule_plan_ppmschedule_schedule_reason_and_more'),
        ('scheduling', '0001_initial'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            lambda apps, se: retire_surplus_open(apps, se, 'ppms', 'PPMSchedule'),
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='ppmschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('active_status', True), ('pending_delete', False), models.Q(('status', 'completed'), _negated=True)), fields=('equipment',), name='ppms_one_open_schedule'),
        ),
    ]
