# Generated by Django 5.2.15 on 2026-09-28 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='attachment',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='emailoutbox',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting to send'), ('sent', 'Sent'), ('failed', 'Refused'), ('expired', 'Expired unsent'), ('cancelled', 'Discarded')], db_index=True, default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('starttls', 'STARTTLS (port 587)'), ('ssl', 'SSL/TLS (port 465)'), ('none', 'None')], default='starttls', max_length=8)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, help_text='Sender address; the username when blank.', max_length=254)),
                ('is_site_sender', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
